### ISSUE TITLE
As a user, I want to be able to check product details (1 point)

### ISSUE THREAD

**Issue by CarlaShawi** [raccoonrick/SOEN341#11]
User Story:

As a user, I want to be able to see a full description of the product details, i.e. price, weight, ingredients, description.

Tasks:
- Create front-end design for the product page.
- Add price and description for each product
- Add pictures of each product 
- Add to cart button option

To track progress refer to epic #6

**Comment by J-P-engdev** [comment]
The frontend team has created many product pages with descriptions and details. Therefore, this issue can now be closed. Note that new products will be added in the future.

**Comment by Tharsipa** [comment]
Reopened this issue to fix minor issues related to the header and added a description button

**Comment by Tharsipa** [comment]
The product description button works well for all 18 product pages.
