### ISSUE TITLE
Determine the size (story points) of all user stories.

### ISSUE THREAD

**Issue by J-P-engdev** [raccoonrick/SOEN341#24]
The team should meet to assign a level of effort for each user story and determine the acceptance criteria.
The subtasks for each user stories and their story points will be determined later.

**Comment by CarlaShawi** [comment]
I'm okay with a meeting tomorrow after 8 pm because I have work earlier.  Or next Monday at any time after 4 pm.

**Comment by superdina68** [comment]
I have class tomorrow from 5:45 to 10:25, but Friday, Saturday or Sunday no problem for me, and Monday after 4 sounds great too.

**Comment by FidaInthesar** [comment]
Monday after 4 pm sounds great

**Comment by superdina68** [comment]
@J-P-engdev this can be closed once the story points are set, correct?

**Comment by J-P-engdev** [comment]
This was done for sprint#2 and is completed.
