### ISSUE TITLE
user stories

### ISSUE THREAD

**Issue by Ahed752** [raccoonrick/SOEN341#5]
1) As an online customer, I need to search for products, so that I can find the ones I want to buy.
acceptance criteria: 
   * Search for a product by name or category.
   * View products by category.
   * View images and details for each product.
   * Add to cart from the detail or search pages.

	  2) As a seller, I need to Add products to my e-store so that I can improve my trades profits
acceptance criteria: 
   * Admin added new products to the store.
   * Admin changed the quality available of the products.
   * Admin removed products.

  	3) As a customer, I need to authenticate myself so that I can see my account details and past orders.
acceptance criteria: 
   * User entered the correct credentials for authentication.
   * User realizes that they forgot the credentials.
   * User realizes that they do not have an account, and wants to create one now.
   * user creates orders and add payment methods.

**Comment by J-P-engdev** [comment]
User stories were reformatted as individual issues.
