### ISSUE TITLE
As a user, I want to be able to log in and register as administrator or a normal user (2 points)

### ISSUE THREAD

**Issue by CarlaShawi** [raccoonrick/SOEN341#9]
User Story:

As a user, I want to be able to log in and register as administrator or a normal user.

Tasks:

-Create Database for users
-Create login and register pages
-Write frontend and backend code
-Link the login page and the register page.

To track progress refer to epic #6

**Comment by CarlaShawi** [comment]
Assessed at the beginning of Sprint 2

Associated Tasks:
-Create front end design for login & register page

**Comment by CarlaShawi** [comment]
login page html and css design were added to a new branch called frontend1.

**Comment by superdina68** [comment]
Header and Footer added.

**Comment by CarlaShawi** [comment]
the css needs to be modified so that the colors coordinate with the header and footer.

**Comment by J-P-engdev** [comment]
The frontend and backend functionalities of this user story have been implemented. We need to merge it onto the main branch.
